# -*- coding: utf-8 -*-
"""transformation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSlVeagh0aBteZEaRkPQ0d9Y5jJ1Oslv
"""

import pandas as pd

# Load the A-Level results data from the CSV file
df = pd.read_csv('/content/AL.csv')

# Display the first 5 rows of the DataFrame
display(df.head())

# Display general information about the DataFrame
print(df.info())

# Display descriptive statistics of the DataFrame
display(df.describe())

# Function to clean and convert columns to numeric
def clean_and_convert_numeric(df, columns):
    for col in columns:
        # Remove non-numeric characters (like '(NEW)' or extra spaces) from the column
        df[col] = df[col].astype(str).str.replace(r'[^\d.-]+', '', regex=True)
        # Convert to numeric, coercing errors to NaN
        df[col] = pd.to_numeric(df[col], errors='coerce')
    return df

# Columns to clean and convert
numeric_cols = ['Zscore', 'district_rank', 'island_rank']
df = clean_and_convert_numeric(df, numeric_cols)

# Display the info and head of the DataFrame to confirm changes
print(df.info())
display(df.head())

# Impute missing values in 'Zscore', 'district_rank', and 'island_rank' with their respective means
df['Zscore'] = df['Zscore'].fillna(df['Zscore'].mean())
df['district_rank'] = df['district_rank'].fillna(df['district_rank'].mean())
df['island_rank'] = df['island_rank'].fillna(df['island_rank'].mean())

# Impute missing values in 'gender' with its mode
df['gender'] = df['gender'].fillna(df['gender'].mode()[0])

# Display the info of the DataFrame to confirm changes in null counts and data types
print(df.info())

# Calculate the average Z-score for each stream
stream_performance = df.groupby('stream')['Zscore'].mean().sort_values(ascending=False)

print("\nAverage Z-score per Stream:")
display(stream_performance)

# Calculate the average Z-score for each district
district_performance = df.groupby('district_rank')['Zscore'].mean().sort_values(ascending=False)

print("\nTop 10 Districts by Average Z-score:")
display(district_performance.head(10))

import matplotlib.pyplot as plt
import seaborn as sns

# Visualize the top 10 districts by average Z-score
plt.figure(figsize=(12, 6))
sns.barplot(x=district_performance.head(10).index, y=district_performance.head(10).values, hue=district_performance.head(10).index, palette='viridis', legend=False)
plt.title('Top 10 Districts by Average Z-score')
plt.xlabel('District Rank')
plt.ylabel('Average Z-score')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()